-- 1
CREATE TABLE CATEGORY
(CatCode Varchar2(2),
CatDesc Varchar2(10));
-- 2
CREATE TABLE EMPLOYEES
(Emp# Number(5), 
Lastname Varchar2(15), 
Firstname Varchar2(15), 
Job_class Varchar2(4));
-- 3
ALTER TABLE EMPLOYEES ADD (EmpDate DATE DEFAULT SYSDATE);
ALTER TABLE EMPLOYEES ADD (EndDate DATE);
-- 4
ALTER TABLE EMPLOYEES MODIFY Job_class Varchar2(2);
-- 5
ALTER TABLE EMPLOYEES DROP COLUMN ENDDATE;
-- 6
RENAME EMPLOYEES TO JL_EMPS;
-- 7
CREATE TABLE BOOK_PRICING (ID, COST, RETAIL, CATEGORY) AS 
SELECT ISBN, COST, RETAIL,  CATEGORY
FROM BOOKS;
-- 8
ALTER TABLE BOOK_PRICING
SET UNUSED COLUMN CATEGORY;
SELECT CATEGORY FROM BOOK_PRICING;
SELECT * FROM BOOK_PRICING;
-- 9
TRUNCATE TABLE BOOK_PRICING;
SELECT * FROM BOOK_PRICING;
-- 10
ALTER SESSION SET RECYCLEBIN = ON;
DROP TABLE BOOK_PRICING PURGE;
DROP TABLE JL_EMPS;
FLASHBACK TABLE JL_EMPS TO BEFORE DROP;
SELECT * from EMPLOYEES;
-- 11
CREATE TABLE store_reps
(rep_ID NUMBER(5) PRIMARY KEY,
last VARCHAR2(15),
first VARCHAR2(10),
comm CHAR(1) DEFAULT 'Y');
-- 12
ALTER TABLE store_reps
MODIFY last VARCHAR2(15) NOT NULL;
ALTER TABLE store_reps
MODIFY first VARCHAR2(10) NOT NULL;
-- 13
ALTER TABLE  store_reps
ADD CONSTRAINT  choice_in_comm
CHECK (comm  IN ('Y', 'N'));
-- 14
ALTER TABLE store_reps 
ADD Base_Salary NUMBER(7, 2)
CONSTRAINT salary_check CHECK (Base_Salary>0);
-- 15
CREATE TABLE BOOK_STORES 
(STORE_ID NUMBER(8),
NAME Varchar2(30) NOT NULL,
CONTACT VARCHAR2(30),
REP_ID VARCHAR2(5),
CONSTRAINT book_stores_primarykey PRIMARY KEY (STORE_ID),
CONSTRAINT name_book_unique UNIQUE (NAME));
-- 16
ALTER TABLE BOOK_STORES MODIFY (REP_ID NUMBER(5));
ALTER TABLE BOOK_STORES
ADD CONSTRAINT rep_id_foreignkey FOREIGN KEY (REP_ID) REFERENCES STORE_REPS (REP_ID);
-- 17
ALTER TABLE BOOK_STORES DROP CONSTRAINT rep_id_foreignkey;
ALTER TABLE BOOK_STORES ADD CONSTRAINT rep_id_foreignkey 
FOREIGN KEY (REP_ID) REFERENCES STORE_REPS (REP_ID) ON DELETE CASCADE;
--18
CREATE TABLE REP_CONTRACTS
(STORE_ID NUMBER(8),
NAME NUMBER(5),
QUARTER CHAR(3),
REP_ID NUMBER(5),
CONSTRAINT rep_contracts_primarykey PRIMARY KEY (STORE_ID, REP_ID, QUARTER),
CONSTRAINT store_id_foreingkey FOREIGN KEY (STORE_ID) REFERENCES BOOK_STORES (STORE_ID),
CONSTRAINT rep_id_foreingkey FOREIGN KEY (REP_ID) REFERENCES STORE_REPS (REP_ID));
-- 19
SELECT * FROM user_constraints
WHERE table_name = 'STORE_REPS';
-- 20
ALTER TABLE STORE_REPS DISABLE CONSTRAINT SALARY_CHECK;
SELECT * FROM user_constraints
WHERE table_name = 'STORE_REPS';
ALTER TABLE STORE_REPS ENABLE CONSTRAINT SALARY_CHECK;
SELECT * FROM user_constraints
WHERE table_name = 'STORE_REPS';